server:
  port: 8080

spring:
  application:
    name: catalog-microservice
  
logging:
  level:
    com.techtrend.catalog: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always